using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using EchoCradle.Interview;
using Microsoft.Extensions.AI;
using ModelContextProtocol.Server;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

// This is a metadata/binding compiler, not a second MCP server or transport.
string root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../"));
string output = Path.Combine(root, "Unity/Assets/Scripts/Interview/InterviewToolBindings.g.cs");
bool check = args.Length == 1 && args[0] == "--check";
bool print = args.Length == 1 && args[0] == "--print";
if (args.Length != 0 && !check && !print)
    throw new ArgumentException("Usage: ToolDefinitions [--check|--print]");
MethodInfo[] methods = typeof(InterviewState).GetMethods(BindingFlags.Public | BindingFlags.Instance)
    .Where(method => method.GetCustomAttribute<McpServerToolAttribute>() != null)
    .OrderBy(method => method.Name, StringComparer.Ordinal).ToArray();
if (methods.Length == 0) throw new InvalidOperationException("No attributed tools found.");
var declarations = new JArray();
var names = new HashSet<string>(StringComparer.Ordinal);
var cases = new StringBuilder();
foreach (MethodInfo method in methods)
{
    ParameterInfo[] parameters = method.GetParameters();
    // Intentionally bounded binder. Fail generation rather than silently misbind a new signature.
    if (method.ReturnType != typeof(JObject) || parameters.Any(parameter =>
            parameter.ParameterType != typeof(string) || parameter.IsOptional || parameter.IsOut))
        throw new InvalidOperationException($"Unsupported synchronous tool signature: {method.Name}");
    var target = new InterviewState(new JObject
    {
        ["type"] = "object", ["additionalProperties"] = false,
        ["required"] = new JArray(), ["properties"] = new JObject()
    });
    McpServerTool tool = McpServerTool.Create(method, target, new McpServerToolCreateOptions
    {
        SchemaCreateOptions = new AIJsonSchemaCreateOptions { TransformOptions = new()
        {
            DisallowAdditionalProperties = true
        } }
    });
    string name = tool.ProtocolTool.Name;
    if (!names.Add(name)) throw new InvalidOperationException($"Duplicate tool: {name}");
    JObject schema = JObject.Parse(tool.ProtocolTool.InputSchema.GetRawText());
    if (schema.DescendantsAndSelf().OfType<JProperty>().Any(property =>
            property.Name is "$ref" or "$dynamicRef" or "$recursiveRef"))
        throw new InvalidOperationException("Reference-bearing schemas are not supported by the wire.");
    declarations.Add(new JObject
    {
        ["type"] = "function", ["function"] = new JObject
        {
            ["name"] = name, ["description"] = tool.ProtocolTool.Description,
            ["parameters"] = schema
        }
    });
    string Quote(string value) => JsonConvert.ToString(value);
    cases.AppendLine($"                case {Quote(name)}:");
    string guards = string.Join(" || ", parameters.Select(parameter =>
        $"arguments[{Quote(parameter.Name!)}]?.Type != JTokenType.String"));
    cases.AppendLine($"                    if (arguments.Count != {parameters.Length} || {guards})");
    cases.AppendLine("                        return new JObject { [\"error\"] = \"invalid_arguments\" };");
    string arguments = string.Join(", ", parameters.Select(parameter =>
        $"(string)arguments[{Quote(parameter.Name!)}]"));
    cases.AppendLine($"                    return target.{method.Name}({arguments});");
}
string json = declarations.ToString(Formatting.None).Replace("\"", "\"\"");
string inputPath = Path.Combine(root, "Unity/Assets/Scripts/Interview/InterviewState.cs");
string inputHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(
    File.ReadAllText(inputPath).Replace("\r\n", "\n"))));
string source = $$"""
// <auto-generated>Generated by tools/ToolDefinitions using the official MCP C# SDK.</auto-generated>
// Input SHA256: {{inputHash}}
using Newtonsoft.Json.Linq;

namespace EchoCradle.Interview
{
    internal static class InterviewToolBindings
    {
        internal static JArray Declarations() => JArray.Parse(@"{{json}}");

        internal static JObject Invoke(InterviewState target, string name, JObject arguments)
        {
            if (arguments == null) return new JObject { ["error"] = "invalid_arguments" };
            switch (name)
            {
{{cases.ToString().TrimEnd()}}
                default:
                    return new JObject { ["error"] = "invalid_arguments" };
            }
        }
    }
}
""";
source = source.Replace("\r\n", "\n") + "\n";
if (print) Console.Write(source);
else if (check)
{
    if (!File.Exists(output) || File.ReadAllText(output).Replace("\r\n", "\n").TrimEnd() != source.TrimEnd())
        throw new InvalidOperationException("Generated tool bindings are stale; run ToolDefinitions.");
    Console.WriteLine("Official MCP SDK tool declarations and direct bindings are up to date.");
}
else
{
    // Emission is performed by this explicit source generator, never at game runtime.
    File.WriteAllText(output, source, new UTF8Encoding(false));
    Console.WriteLine($"Generated {methods.Length} tool declaration(s) and direct bindings.");
}