// <auto-generated>Generated by tools/ToolDefinitions using the official MCP C# SDK.</auto-generated>
// Input SHA256: 49AB9A51F192D6AD30A5D9EE78E077C914C4CDBAC61DEB374FA0294720826BD2
using Newtonsoft.Json.Linq;

namespace EchoCradle.Interview
{
    internal static class InterviewToolBindings
    {
        internal static JArray Declarations() => JArray.Parse(@"[{""type"":""function"",""function"":{""name"":""config_set"",""description"":""Record a confirmed player preference. A correction replaces the previous value. Never invent values. Returns recorded values and missing required fields."",""parameters"":{""type"":""object"",""properties"":{""field"":{""description"":""The configured player preference field to record."",""type"":""string""},""value"":{""description"":""The value supplied or confirmed by the player."",""type"":""string""}},""required"":[""field"",""value""],""additionalProperties"":false}}}]");

        internal static JObject Invoke(InterviewState target, string name, JObject arguments)
        {
            if (arguments == null) return new JObject { ["error"] = "invalid_arguments" };
            switch (name)
            {
                case "config_set":
                    if (arguments.Count != 2 || arguments["field"]?.Type != JTokenType.String || arguments["value"]?.Type != JTokenType.String)
                        return new JObject { ["error"] = "invalid_arguments" };
                    return target.RecordPreference((string)arguments["field"], (string)arguments["value"]);
                default:
                    return new JObject { ["error"] = "invalid_arguments" };
            }
        }
    }
}